
services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./data1:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - 27018:27017
    volumes:
      - ./data2:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-net

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - 27019:27017
    volumes:
      - ./data3:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - mongo-net


  jupyter-textmining:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./script_python:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge